# Generated by Django 5.0.2 on 2024-02-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='color',
            field=models.CharField(blank=True, choices=[('White', 'White'), ('Blue', 'Blue'), ('Red', 'Red'), ('Yellow', 'Yellow')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images'),
        ),
        migrations.AddField(
            model_name='productsmodel',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
