# Generated by Django 5.0.2 on 2024-03-22 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productsmodel_color_productsmodel_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='rating',
        ),
    ]
